name: Expose RDP via ngrok

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download ngrok
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip -DestinationPath .

    - name: Authenticate with ngrok
      run: |
        ./ngrok authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}  # Set ngrok auth token in GitHub Secrets

    - name: Start ngrok TCP Tunnel
      run: |
        ./ngrok tcp 3389

    # Additional steps here as needed for your workflow
