name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Tailscale
      run: |
        curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/focal.gpg | sudo apt-key add -
        curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/focal.list | sudo tee /etc/apt/sources.list.d/tailscale.list
        sudo apt-get update
        sudo apt-get install tailscale
        sudo tailscale up --authkey ${{ secrets.TAILSCALE_AUTH_KEY }}
        # Keep tailscaled running in the background using screen
        screen -d -m sudo tailscaled
        # Optional: Start tailscale if not already started
        sudo tailscale up --accept-dns=false

    - name: Enable Remote Desktop
      run: |
        sudo apt-get update
        sudo apt-get install -y xrdp
        sudo systemctl enable --now xrdp
        sudo ufw allow 3389
        echo "runneradmin:P@ssw0rd!" | sudo chpasswd

    - name: Display Tailscale Status
      run: sudo tailscale status
      
    - name: Long Running Process
      run: |
        while true; do
          echo "Running some task..."
          sleep 300  # Sleep for 5 minutes
        done
