name: Expose RDP via Serveo

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install SSH client
      run: sudo apt-get install openssh-client -y  # Install SSH client if not already installed

    - name: Open Serveo Tunnel
      run: ssh -R 3389:localhost:3389 serveo.net

    # Add steps here to configure and start your RDP service, if needed
