name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install ZeroTier
      run: |
        sudo apt-get update
        sudo apt-get install -y curl
        curl -s https://install.zerotier.com | sudo bash
        sudo zerotier-cli join 9f77fc393e61935c  # Replace <NETWORK_ID> with your actual ZeroTier Network ID
        sudo systemctl enable zerotier-one
        sudo systemctl restart zerotier-one
      env:
        NETWORK_ID: 9f77fc393e61935c
        # Optionally, you can add your ZeroTier auth token as a secret
        ZT_AUTH_TOKEN: ${{ secrets.ZT_AUTH_TOKEN }}

    - name: Enable Remote Desktop
      run: |
        sudo apt-get update
        sudo apt-get install -y xrdp
        sudo systemctl enable --now xrdp
        sudo ufw allow 3389
        echo "runneradmin:P@ssw0rd!" | sudo chpasswd

    - name: Display ZeroTier Status
      run: sudo zerotier-cli info
