name: Expose RDP via Serveo

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Install PuTTY
      run: |
        choco install putty.portable -y  # Install PuTTY via Chocolatey

    - name: Open Serveo Tunnel
      run: |
        echo y | plink.exe -N -R 3389:localhost:3389 serveo.net -l your_username -pw your_password

    # Add steps here to configure and start your RDP service, if needed
